title: "健康作息时间表 - 科学作息，健康生活"
description: "提供权威的健康作息时间表服务，整理世界卫生组织WHO、哈佛大学、清华大学及知名企业家的作息建议，科学作息，健康生活！"
baseurl: /
url: "https://zuoxibiao.com"

# Build settings
markdown: kramdown
highlighter: rouge
timezone: Asia/Shanghai

# Collections and data
collections_dir: _data

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from build
exclude:
  - README.md
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache

# Include files
include:
  - _data

# Sass settings
sass:
  style: compressed
  sass_dir: _sass

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site settings for SEO
author: ZuoXiBiao.com
lang: zh-CN

# Social and sharing
social:
  name: ZuoXiBiao.com
  links:
    - https://zuoxibiao.com